language: go
go:
- 1.9.4
- '1.10'
sudo: required
install:
- sudo add-apt-repository -y ppa:bitcoin/bitcoin -y
- sudo apt-get update -q
- sudo apt-get install bitcoind -y
- export PATH=$PATH:$PWD/linux-amd64/
script:
- export PATH=$PATH:$GOPATH/bin
- make dep
- ./mobile/build_mobile.sh
deploy:
  provider: releases
  api_key:
    secure: Aik8HpRn4uhrCdrlwA5GQEjw9npklOAJSMuYqpEFd707aSuixly8vYg0yS3e68f53R+gH/OQ7qFCtYNsCiUSinvaKbFlXgCJ5kwnMWX7cOOTy95l/IOKV6LMQcyWip+X7Id0ts6EyRUcEOKajvv1pGtKDyjT4ohhHw6qo1G6p7FA5OHlppGljJObHaHjL0alLo2CQZfHHxxI9Mu9Hcx2lTbRcIvbuYAsfQfT1Rhw6Nq2vRcLBU9o0FSzHCxQKlZI6A9sF9l2dAS5qB5FLZVYibS/VxzwR3M7uSRvVYoSm9pDTpZ9sIE+DQpIHA9HvBxlHrNCgfV+E+36AUCnC/BmSq3BBwTqe+PXynKa5bVRTREUxG8+YvsgwpXnLfgDr5USEKj9ZxnW6gEot6kV2pmAnqIMvaPKvmTRoQCWITv+AJiQYW1UFEq3SGgNf5AbM6eicBcgDqv1c0ho1Ci7Xeo1guw47JXr8rBGhdWZsoSQASxc5MiBcia9m6IfCd3o4tJbcR3mSkgwL25nCcoFQQQq1cflX9hv7kWNw7STbB7JGJredZquSSdHOeZI6/XrmHP2U5GmGs94NA73b9ttgV7LBiz0WGbwKTQwCA+v6kn81NjQ1mqpXEsDrLgbuZSwSJkPd0bJN415DyQkOtN3ImkJOyIqRDaPgLdDdy8r0NWRRtk=
  file: mobile/build/ios/Lndmobile.framework
  skip_cleanup: true
  on:
    tags: true
    repo: ottosuess/lnd
